In [1]:
from pathlib import Path
import pandas as pd

In [39]:
BASE_DIR=Path("..")/'data'
identity=pd.read_csv(BASE_DIR/'test_identity.csv', index_col='TransactionID')
transaction=pd.read_csv(BASE_DIR/'test_transaction.csv', index_col='TransactionID')
transaction_train=pd.read_csv(BASE_DIR/'train_transaction.csv', index_col='TransactionID')
identity_train=pd.read_csv(BASE_DIR/'train_identity.csv', index_col='TransactionID')

In [52]:
identity

,id-01,id-02,id-03,id-04,id-05,id-06,id-07,id-08,id-09,id-10,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
3663586,-45.0,280290.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,chrome 67.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,MYA-L13 Build/HUAWEIMYA-L13
3663588,0.0,3579.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,...,chrome 67.0 for android,24.0,1280x720,match_status:2,T,F,T,T,mobile,LGLS676 Build/MXB48T
3663597,-5.0,185210.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,...,ie 11.0 for tablet,NaN,NaN,NaN,F,T,T,F,desktop,Trident/7.0
3663601,-45.0,252944.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,...,chrome 67.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,MYA-L13 Build/HUAWEIMYA-L13
3663602,-95.0,328680.0,NaN,NaN,7.0,-33.0,NaN,NaN,NaN,NaN,...,chrome 67.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-G9650 Build/R16NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4170230,-20.0,473365.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J700M
4170233,-5.0,489917.0,0.0,0.0,-4.0,-32.0,NaN,NaN,0.0,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J320M
4170234,-5.0,110081.0,NaN,NaN,22.0,-31.0,NaN,NaN,NaN,NaN,...,mobile safari 10.0,32.0,1334x750,match_status:2,T,F,F,T,mobile,iOS Device
4170236,-45.0,266704.0,NaN,NaN,-3.0,-10.0,NaN,NaN,NaN,NaN,...,chrome 43.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,ALE-L23 Build/HuaweiALE-L23
4170239,-10.0,692090.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,...,samsung browser 8.2,NaN,NaN,NaN,F,F,T,F,mobile,SAMSUNG

In [43]:
identity.info()
identity_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 141907 entries, 3663586 to 4170239
Data columns (total 40 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id-01       141907 non-null  float64
 1   id-02       136976 non-null  float64
 2   id-03       66481 non-null   float64
 3   id-04       66481 non-null   float64
 4   id-05       134750 non-null  float64
 5   id-06       134750 non-null  float64
 6   id-07       5059 non-null    float64
 7   id-08       5059 non-null    float64
 8   id-09       74338 non-null   float64
 9   id-10       74338 non-null   float64
 10  id-11       136778 non-null  float64
 11  id-12       141907 non-null  object
 12  id-13       130286 non-null  float64
 13  id-14       71357 non-null   float64
 14  id-15       136977 non-null  object
 15  id-16       125747 non-null  object
 16  id-17       135966 non-null  float64
 17  id-18       50875 non-null   float64
 18  id-19       135906 non-null  float64
 19  id-20       135633 non-null  float64
 20  id-21       5059 non-null    float64
 21  id-22       5062 non-null    float64
 22  id-23       5062 non-null    object
 23  id-24       4740 non-null    float64
 24  id-25       5039 non-null    float64
 25  id-26       5047 non-null    float64
 26  id-27       5062 non-null    object
 27  id-28       136778 non-null  object
 28  id-29       136778 non-null  object
 29  id-30       70659 non-null   object
 30  id-31       136625 non-null  object
 31  id-32       70671 non-null   float64
 32  id-33       70671 non-null   object
 33  id-34       72175 non-null   object
 34  id-35       136977 non-null  object
 35  id-36       136977 non-null  object
 36  id-37       136977 non-null  object
 37  id-38       136977 non-null  object
 38  DeviceType  136931 non-null  object
 39  DeviceInfo  115057 non-null  object
dtypes: float64(23), object(17)
memory usage: 44.4+ MB
<class 'pandas.core.frame.DataFrame'>
Index: 144233 entries, 2987004 to 3577534
Data columns (total 40 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id_01       144233 non-null  float64
 1   id_02       140872 non-null  float64
 2   id_03       66324 non-null   float64
 3   id_04       66324 non-null   float64
 4   id_05       136865 non-null  float64
 5   id_06       136865 non-null  float64
 6   id_07       5155 non-null    float64
 7   id_08       5155 non-null    float64
 8   id_09       74926 non-null   float64
 9   id_10       74926 non-null   float64
 10  id_11       140978 non-null  float64
 11  id_12       144233 non-null  object
 12  id_13       127320 non-null  float64
 13  id_14       80044 non-null   float64
 14  id_15       140985 non-null  object
 15  id_16       129340 non-null  object
 16  id_17       139369 non-null  float64
 17  id_18       45113 non-null   float64
 18  id_19       139318 non-null  float64
 19  id_20       139261 non-null  float64
 20  id_21       5159 non-null    float64
 21  id_22       5169 non-null    float64
 22  id_23       5169 non-null    object
 23  id_24       4747 non-null    float64
 24  id_25       5132 non-null    float64
 25  id_26       5163 non-null    float64
 26  id_27       5169 non-null    object
 27  id_28       140978 non-null  object
 28  id_29       140978 non-null  object
 29  id_30       77565 non-null   object
 30  id_31       140282 non-null  object
 31  id_32       77586 non-null   float64
 32  id_33       73289 non-null   object
 33  id_34       77805 non-null   object
 34  id_35       140985 non-null  object
 35  id_36       140985 non-null  object
 36  id_37       140985 non-null  object
 37  id_38       140985 non-null  object
 38  DeviceType  140810 non-null  object
 39  DeviceInfo  118666 non-null  object
dtypes: float64(23), object(17)
memory usage: 45.1+ MB

In [ ]:
print('transaction_test: ')
transaction.info()
print('transaction_train:')
transaction_train.info()

transaction_test:
<class 'pandas.core.frame.DataFrame'>
Index: 506691 entries, 3663549 to 4170239
Columns: 392 entries, TransactionDT to V339
dtypes: float64(376), int64(2), object(14)
memory usage: 1.5+ GB
transaction_train:
<class 'pandas.core.frame.DataFrame'>
Index: 590540 entries, 2987000 to 3577539
Columns: 393 entries, isFraud to V339
dtypes: float64(376), int64(3), object(14)
memory usage: 1.7+ GB

In [ ]:
# identity NA count
na_counts_identity=identity.isna().sum()
na_summary_identity=pd.DataFrame({'NA_Count': na_counts_identity,})
#na_summary_identity=na_summary_identity[na_summary_identity["NA_Count"] > 0].sort_values("NA_Count", ascending=False)

na_summary_identity

            NA_Count
id-01              0
id-02           4931
id-03          75426
id-04          75426
id-05           7157
id-06           7157
id-07         136848
id-08         136848
id-09          67569
id-10          67569
id-11           5129
id-12              0
id-13          11621
id-14          70550
id-15           4930
id-16          16160
id-17           5941
id-18          91032
id-19           6001
id-20           6274
id-21         136848
id-22         136845
id-23         136845
id-24         137167
id-25         136868
id-26         136860
id-27         136845
id-28           5129
id-29           5129
id-30          71248
id-31           5282
id-32          71236
id-33          71236
id-34          69732
id-35           4930
id-36           4930
id-37           4930
id-38           4930
DeviceType      4976
DeviceInfo     26850

In [51]:
na_counts_transaction_train=transaction_train.isna().sum()
na_counts_transaction_train=pd.DataFrame({"NA_Count": na_counts_transaction_train})
# After filtering, 300 rows have at least 3000 NAs, and a maximum of 470255
na_counts_transaction_train=na_counts_transaction_train[na_counts_transaction_train["NA_Count"] > 12].sort_values("NA_Count", ascending=False)

na_counts_transaction_train

       NA_Count
dist2    552913
D7       551623
D13      528588
D14      528353
D12      525823
...         ...
V113        314
V112        314
V111        314
V110        314
V137        314

[342 rows x 1 columns]

In [ ]:
na_counts_transaction=transaction.isna().sum()
na_summary_transaction=pd.DataFrame({"NA_Count": na_counts_transaction})
# After filtering, 300 rows have at least 3000 NAs, and a maximum of 470255
na_summary_transaction=na_summary_transaction[na_summary_transaction["NA_Count"] > 3].sort_values("NA_Count", ascending=False)

na_summary_transaction

       NA_Count
dist2    470255
D7       446558
D12      437437
D9       432353
D8       432353
...         ...
C13        4748
card5      4547
card4      3086
card6      3007
card3      3002

[300 rows x 1 columns]

In [53]:
train = transaction_train.join(identity_train, how="left")

In [65]:
transaction_train

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
TransactionID,,,,,,,,,,,,,,,,,,,,,
2987000,0,86400,68.50,W,13926,NaN,150.0,discover,142.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987001,0,86401,29.00,W,2755,404.0,150.0,mastercard,102.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987002,0,86469,59.00,W,4663,490.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987003,0,86499,50.00,W,18132,567.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987004,0,86506,50.00,H,4497,514.0,150.0,mastercard,102.0,credit,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577535,0,15811047,49.00,W,6550,NaN,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3577536,0,15811049,39.50,W,10444,225.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3577537,0,15811079,30.95,W,12037,595.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3577538,0,15811088,117.00,W,7826,481.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3577539,0,15811131,279.95,W,15066,170.0,150.0,mastercard,102.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
identity_train

,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577521,-15.0,145955.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,F3111 Build/33.3.A.1.97
3577526,-5.0,172059.0,NaN,NaN,1.0,-5.0,NaN,NaN,NaN,NaN,...,chrome 55.0 for android,32.0,855x480,match_status:2,T,F,T,F,mobile,A574BL Build/NMF26F
3577529,-20.0,632381.0,NaN,NaN,-1.0,-36.0,NaN,NaN,NaN,NaN,...,chrome 65.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Moto E (4) Plus Build/NMA26.42-152
3577531,-5.0,55528.0,0.0,0.0,0.0,-7.0,NaN,NaN,0.0,0.0,...,chrome 66.0,24.0,2560x1600,match_status:2,T,F,T,F,desktop,MacOS
3577534,-45.0,339406.0,NaN,NaN,-10.0,-100.0,NaN,NaN,NaN,NaN,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,RNE-L03 Build/HUAWEIRNE-L03

In [64]:
train

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
2987000,0,86400,68.50,W,13926,NaN,150.0,discover,142.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987001,0,86401,29.00,W,2755,404.0,150.0,mastercard,102.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987002,0,86469,59.00,W,4663,490.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987003,0,86499,50.00,W,18132,567.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987004,0,86506,50.00,H,4497,514.0,150.0,mastercard,102.0,credit,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3577535,0,15811047,49.00,W,6550,NaN,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3577536,0,15811049,39.50,W,10444,225.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3577537,0,15811079,30.95,W,12037,595.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3577538,0,15811088,117.00,W,7826,481.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3577539,0,15811131,279.95,W,15066,170.0,150.0,mastercard,102.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
na_counts = train.isna().sum()
na_summary = pd.DataFrame({
    "NA_Count": na_counts,
    "NA_Percent": train.isna().mean() * 100
    })
# After filtering, 300 rows have at least 3000 NAs, and a maximum of 470255
na_summary = na_summary[na_summary["NA_Percent"] > 10].sort_values("NA_Count", ascending=False)

na_summary

       NA_Count  NA_Percent
id_24    585793   99.196159
id_25    585408   99.130965
id_08    585385   99.127070
id_07    585385   99.127070
id_21    585381   99.126393
...         ...         ...
V15       76073   12.881939
V14       76073   12.881939
D10       76022   12.873302
addr2     65706   11.126427
addr1     65706   11.126427

[322 rows x 2 columns]